"""
Baby block.

Included only on configured creche days (default Tue–Fri).
Drop-off (08:00) and pick-up (16:15) weather at the creche location.
Clothing recommendation generated by Claude Haiku, calibrated to baby's
current age and pushchair travel (per SPEC §3.1).

Phase 11 addition: midday alert detection.
  - Any hour in midday_alert_window with rain_snow_threshold_pct ≥ 40%
    triggers an alert string in block["alerts"].
  - Soft-rule LLM alerts deferred to v2 (SPEC §15).

Block return shape:
    {
        "location":         {"postcode": ..., "city": ...},
        "date":             "Tuesday, 26 May 2026",
        "weekday":          "Tue",
        "baby_age_months":  4.5,
        "drop_off": {"time": "08:00", "temp_c": ..., "wind_ms": ..., "wind_dir": ...,
                     "rain_pct": ..., "cloud_label": ...},
        "pick_up":  {"time": "16:15", ...},
        "alerts":   ["⚠ Rain likely 09:00–16:00 (peak 70%)"],  # [] if none
        "clothing": {
            "outfit":             "...",
            "pushchair_extras":   "...",
            "pick_up_note":       "...",
        },
    }

Returns None if target_date is NOT a creche day (digest renderer skips Nones).
Also returns None if the weather fetch fails.
"""

from datetime import date as date_cls
from agent.fetchers.weather import fetch_hourly, filter_hours, degrees_to_compass
from agent.llm import baby_clothing_recommendation


WEEKDAY_ABBREV = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def _cloud_label(cloud_pct, labels_cfg):
    if cloud_pct is None:
        return "unknown"
    for label, (lo, hi) in labels_cfg.items():
        if lo <= cloud_pct <= hi:
            return label
    return "unknown"


def _age_in_months(birthdate, target_date):
    """Approximate age in months — good enough for clothing decisions."""
    if isinstance(birthdate, str):
        birthdate = date_cls.fromisoformat(birthdate)
    days = (target_date - birthdate).days
    return round(days / 30.44, 1)


def _weather_summary(w, time_label, cloud_labels_cfg):
    """Compact weather dict for one time slot."""
    return {
        "time": time_label,
        "temp_c": w["temperature_c"],
        "wind_ms": w["windspeed_ms"],
        "wind_dir": degrees_to_compass(w["winddirection_deg"]),
        "rain_pct": w["precipitation_probability_pct"],
        "cloud_label": _cloud_label(w["cloudcover_pct"], cloud_labels_cfg),
    }


def _build_midday_alerts(hourly: list, target_date, creche_cfg: dict) -> list[str]:
    """
    Scan hourly rows for the alert window and return alert strings.

    Rule (SPEC §3.1 hard rule):
        Any hour in midday_alert_window where rain/snow prob ≥
        rain_snow_threshold_pct → alert line.

    Returns a list of human-readable alert strings (often [] if quiet).
    """
    window = creche_cfg.get("midday_alert_window", ["09:00", "16:00"])
    threshold = creche_cfg.get("rain_snow_threshold_pct", 40)

    window_start_h = int(window[0].split(":")[0])  # "09:00" → 9
    window_end_h   = int(window[1].split(":")[0])  # "16:00" → 16

    alert_hours = list(range(window_start_h, window_end_h + 1))
    rows = filter_hours(hourly, target_date, alert_hours)

    # Collect hours that breach the threshold.
    breaching = [
        r for r in rows
        if r.get("precipitation_probability_pct") is not None
        and r["precipitation_probability_pct"] >= threshold
    ]

    if not breaching:
        return []

    # Summarise: report window + peak probability.
    probs = [r["precipitation_probability_pct"] for r in breaching]
    peak  = max(probs)

    # Start/end of the contiguous alert window.
    times = sorted(int(r["time"][11:13]) for r in breaching)
    start_str = f"{times[0]:02d}:00"
    end_str   = f"{times[-1]:02d}:00"

    return [
        f"Rain likely {start_str}–{end_str} (peak {peak}%)"
    ]


def build_baby_block(cfg, target_date):
    baby_cfg  = cfg["baby"]
    creche_cfg = baby_cfg["creche"]

    # Is target_date a creche day?
    weekday = WEEKDAY_ABBREV[target_date.weekday()]
    if weekday not in creche_cfg["days"]:
        return None

    loc = creche_cfg["location"]
    drop_off_time = creche_cfg["drop_off"]   # "08:00"
    pick_up_time  = creche_cfg["pick_up"]    # "16:15"
    cloud_labels_cfg = cfg["cloud_cover_labels"]

    # Fetch hourly weather once — reused for drop-off, pick-up, and alerts.
    try:
        hourly = fetch_hourly(latitude=loc["lat"], longitude=loc["lon"])
    except Exception as e:
        print(f"[baby] weather fetch failed: {e}")
        return None

    drop_off_hour = int(drop_off_time.split(":")[0])
    pick_up_hour  = int(pick_up_time.split(":")[0])
    rows = filter_hours(hourly, target_date, [drop_off_hour, pick_up_hour])

    if len(rows) < 2:
        print(f"[baby] missing weather row(s) for {drop_off_hour} / {pick_up_hour}")
        return None
    w_drop, w_pick = rows[0], rows[1]

    drop_off = _weather_summary(w_drop, drop_off_time, cloud_labels_cfg)
    pick_up  = _weather_summary(w_pick, pick_up_time,  cloud_labels_cfg)

    # Phase 11: midday alerts (hard rule from SPEC §3.1).
    alerts = _build_midday_alerts(hourly, target_date, creche_cfg)

    age_months = _age_in_months(baby_cfg["birthdate"], target_date)

    try:
        clothing = baby_clothing_recommendation(
            age_months=age_months,
            drop_off_weather=drop_off,
            pickup_weather=pick_up,
            midday_alerts=alerts,
        )
    except Exception as e:
        print(f"[baby] LLM clothing call failed: {e}")
        clothing = {
            "outfit": "(LLM unavailable — dress for the listed temperatures, "
                      "remembering pushchair = less self-warming)",
            "pushchair_extras": "",
            "pick_up_note": "",
        }

    return {
        "location":        {"postcode": loc["postcode"], "city": loc["city"]},
        "date":            target_date.strftime("%A, %d %B %Y"),
        "weekday":         weekday,
        "baby_age_months": age_months,
        "drop_off":        drop_off,
        "pick_up":         pick_up,
        "alerts":          alerts,   # list[str], [] if quiet
        "clothing":        clothing,
    }